filebeat.prospectors:
- input_type: log
  paths:
    - /auth.log

filebeat.modules:
- module: nginx
  access:
    var.paths: 
      - /nginx-access.log
      - /nginx-error.log

output.elasticsearch:
  hosts: ["tts.today:9200"]