name: "thebetter.wiki"
tags: ["thebetter.wiki"]


fields_under_root: true
fields:
  application: "thebetter.wiki"

setup.dashboards.enabled: true

filebeat.modules:
- module: nginx
  access:
    var.paths: 
      - /nginx-access.log
  error:
    var.paths: 
      - /nginx-error.log

- module: system
  auth:
    enabled: true
    var.paths: ["/auth.log"]


output.elasticsearch:
  hosts: ["tts.today:9200"]