setup.dashboards.enabled: true

filebeat.modules:
- module: nginx
  access:
    var.paths: 
      - /nginx-access.log
  error:
    var.paths: 
      - /nginx-error.log

- module: system
  auth:
    enabled: true
    var.paths: ["/auth.log"]
    fields: 
      system: thebetter.wiki

output.elasticsearch:
  hosts: ["tts.today:9200"]