setup.dashboards.enabled: true

filebeat.modules:
- module: nginx
  access:
    var.paths: 
      - /nginx-access.log
  error:
    var.paths: 
      - /nginx-error.log

- module: system
  auth:
    prospector:
      fields: 
        application: thebetter.wiki
    enabled: true
    var.paths: ["/auth.log"]


output.elasticsearch:
  hosts: ["tts.today:9200"]