version: '2'
services:
  elasticsearch:
    build: filebeat/
    container_name: filebeat
    volumes:
      - /var/log/auth.log:/auth.log
      - /var/log/nginx/access.log:/nginx-access.log
      - /var/log/nginx/error.log:/nginx-error.log